# Generated by Django 3.2.4 on 2021-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kargo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kargo Ücreti'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stok',
            field=models.IntegerField(default=0, verbose_name='Stok'),
        ),
    ]
